project_id = "riqoyrqxqhhntwovtuwf"

[functions.hls-proxy]
verify_jwt = false

[functions.admin-chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.invite-to-party]
verify_jwt = false
